server.port=8733
spring.datasource.username = postgres
spring.datasource.password = admin
spring.jpa.show-sql=true
spring.flyway.enabled=false

#Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8731/realms/my-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8731/realms/my-realm/protocol/openid-connect/certs


#Kafka
#spring.cloud.stream.function.definition=invoiceConsumer,provisionConsumer
#spring.cloud.stream.bindings.invoiceEventProducer.destination =  invoice-topic
#spring.cloud.stream.bindings.invoiceConsumer-in-0.destination = invoice-topic
#spring.cloud.stream.bindings.invoiceConsumer-in-0.group = group1

#spring.cloud.stream.bindings.provisionEventProducer.destination = provision-topic
#spring.cloud.stream.bindings.provisionConsumer-in-0.destination = provision-topic
#spring.cloud.stream.bindings.provisionConsumer-in-0.group = group2
#spring.cloud.stream.bindings.provisionConsumer-in-0.consumer.concurrency: 1
#spring.cloud.stream.kafka.bindings.provisionConsumer-in-0.consumer.configuration.session.timeout.ms=60000


#Gestion des offsets
#spring.cloud.stream.kafka.binder.consumerProperties.auto.offset.reset=earliest


# Logs
#logging.level.org.springframework.cloud.stream=DEBUG
#logging.level.org.apache.kafka=DEBUG
spring.cloud.stream.dynamicDestinations=invoice-*,provision-*
#spring.kafka.admin.properties.bootstrap.servers=localhost:9093
#spring.cloud.stream.kafka.binder.brokers: localhost:9094
spring.kafka.admin.auto-create=true
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.consumer.group-id=invoice-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
